CONFIG_ZMK_USB=y
CONFIG_NFCT_PINS_AS_GPIOS=y

# Encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK Studio: no unlock key needed (set to y and add &studio_unlock to a key to lock it)
CONFIG_ZMK_STUDIO_LOCKING=n
